
export const Base_Url = 'http://206.189.37.26:8080' 

export const appConstants = {
  API_STATUS_CODE: {
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    REQUEST_TIMEOUT: 408,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVAILABLE: 503,
    GATEWAY_TIMEOUT: 504,
  },
  ASYNC_STORAGE_KEY: {
    PREFERENCES_KEY: 'PREFERENCES_KEY',
    PREV_USER_NAME: 'PREV_USER_NAME',
    USER_TRACKING: 'USER_TRACKING',
    USER_NAME: 'USER_NAME',
  },
  APP_CODE: {
    // From 9000 - 9999
    COMMON_ERROR_CODE: 9999,
    INVALID_ERROR_CODE: 9000,
    PERMISSION_ERROR_CODE: 9001,
  },
  ERROR_CODE: {
    CLIENT_ERROR: 'CLIENT_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    TIMEOUT_ERROR: 'TIMEOUT_ERROR',
    CONNECTION_ERROR: 'CONNECTION_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    CANCEL_ERROR: 'CANCEL_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  },
  FORMAT_DATE_TIME: {
    DDMMYYYY: 'DD-MM-YYYY',
  },
};
